FROM ruby:3.2.0-slim

ENV BUNDLER_VERSION='2.4.12'

RUN apt-get update -qq && apt-get install -y vim\
        curl \
        build-essential \
        libpq-dev \
        postgresql-client \
        redis-server \
        libsqlite3-dev

WORKDIR /survivor-web

COPY Gemfile Gemfile.lock ./

RUN gem install bundler -v $BUNDLER_VERSION \
  && bundle config set --local without 'production' \
  && bundle install

COPY . ./

ENTRYPOINT ["./entrypoints/docker-entrypoint.sh"]
